# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Martin Kowbel Portfolio
email: mekobes44@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 This is my portfolio site, I am an aspiring web developer. I build projects using Javascript, Ruby/Ruby on Rails and Python/Django.
 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: @martykowbel
github_username:  martykobes

# Build settings
markdown: kramdown
